Style/Documentation:
  Enabled: false
Style/MixinUsage:
  Exclude:
    - 'bin/*'

Style/ClassAndModuleChildren:
  Enabled: false
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - !ruby/regexp /old_and_unused\.rb$/
  NewCops: enable
