Style/Documentation:
  Enabled: false
Style/MixinUsage:
  Exclude:
    - 'bin/*'

Style/ClassAndModuleChildren:
  Enabled: false

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - !ruby/regexp /old_and_unused\.rb$/
  NewCops: enable
